### ISSUE TITLE
dont set random keys its against react best practices 

### ISSUE THREAD

**Issue by neopunisher** [keredson/bottle-react#21]
```
    if 'key' not in self.props:
      self.props['key'] = '_br_%f' % random.random()
```

**Comment by keredson** [comment]
this is true as something to avoid *in javascript*.  that's because every new call to render will gen a different key, which causes the diff and dom updater to do much more work than necessary.  but that doesn't apply here.  because we're setting it in python it's fixed throughout the lifecycle of the page, so it's not random at all from react's POV, it's just a weird hard-coded identifier.

**Comment by neopunisher** [comment]
damn your totally right
